[versions]
groovy = "5.0.4"
junit = "6.0.3"
log4j = "2.25.3"
slf4j = "2.0.17"

[libraries]
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy-ant = { module = "org.apache.groovy:groovy-ant", version.ref = "groovy" }
groovy-doc = { module = "org.apache.groovy:groovy-groovydoc", version.ref = "groovy" }
groovy-ginq = { module = "org.apache.groovy:groovy-ginq", version.ref = "groovy" }
groovy-json = { module = "org.apache.groovy:groovy-json", version.ref = "groovy" }
groovy-macro = { module = "org.apache.groovy:groovy-macro", version.ref = "groovy" }
groovy-sql = { module = "org.apache.groovy:groovy-sql", version.ref = "groovy" }
groovy-templates = { module = "org.apache.groovy:groovy-templates", version.ref = "groovy" }
groovy-xml = { module = "org.apache.groovy:groovy-xml", version.ref = "groovy" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
groovier-junit = { module = "se.alipsa.groovy:groovier-junit", version = "0.2.0" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
